import { motion } from 'framer-motion';
import { Download, Share2 } from 'lucide-react';
import type { AnalysisResult } from '../types';

export const ReportGenerator = ({ results }: { results: AnalysisResult }) => {
  const downloadReport = () => {
    const report = `
AI SKIN ANALYSIS REPORT
=======================
Generated: ${new Date().toLocaleString()}

OVERALL ASSESSMENT
------------------
Severity: ${results.severity}
Confidence: ${(results.confidence * 100).toFixed(1)}%
Regions Analyzed: ${results.regions_detected}
Issues Detected: ${results.processed}

REGION-BY-REGION ANALYSIS
--------------------------
${results.regions
  .map(
    (r) => `
${r.display_name}
Issue: ${r.issue}
Confidence: ${r.confidence}%
Severity: ${r.severity}
Recommendation: ${r.recommendation || 'No product needed'}
`
  )
  .join('')}

OVERALL RESULT
--------------
Analysis complete

KEY RECOMMENDATIONS
-------------------
- Consult a dermatologist for persistent issues
- Use products recommended for each region
- Maintain consistent skincare routine
- Protect skin from sun exposure

Generated by AI Skin Analyzer
    `;

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(report));
    element.setAttribute('download', `skin-analysis-${Date.now()}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const shareReport = () => {
    const text = `I just got my skin analyzed! ${results.severity} severity detected in ${results.processed} regions. Check out AI Skin Analyzer!`;
    if (navigator.share) {
      navigator.share({
        title: 'My Skin Analysis',
        text: text,
      });
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(text);
      alert('Report copied to clipboard!');
    }
  };

  return (
    <div className="flex gap-3 flex-wrap">
      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={downloadReport}
        className="px-6 py-2 bg-primary text-white rounded-lg font-semibold flex items-center gap-2 hover:shadow-lg transition"
      >
        <Download size={18} /> Download Report
      </motion.button>
      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={shareReport}
        className="px-6 py-2 border border-primary text-primary rounded-lg font-semibold flex items-center gap-2 hover:bg-primary/5 transition"
      >
        <Share2 size={18} /> Share
      </motion.button>
    </div>
  );
};
